services:
  db:
    image: mysql:8.0
    restart: always
    networks:
      - app-nw
    environment:
      MYSQL_DATABASE: 'cmsschema'
      MYSQL_USER: 'cmsdb1'
      MYSQL_PASSWORD: 'mysqldb1'
      MYSQL_ROOT_PASSWORD: 'mysqldb1'
    ports:
      - '6033:3306'
    expose:
      - '6033'
    volumes:
      - my-db:/var/lib/mysql
  api:
    build: .
    restart: always
    depends_on:
      - db
    networks:
      - app-nw
    environment:
      DATABASE_HOST: db
      DATABASE_NAME: cmsschema
      DATABASE_PASSWORD: mysqldb1
      DATABASE_PORT: 3306
      DATABASE_USERNAME: cmsdb1
      JWT_EXPIRATION_TIME: 3600000
      JWT_SECRET_KEY: 3cfa76ef14937c1c0ea519f8fc057a80fcd04a7420f8e8bcd0a7567c272e007b
    ports:
      - '8080:8080'
    expose:
      - '8080'
volumes:
  my-db:
networks:
  app-nw: